services:
  polen-rest:
    image: python:3.11-slim
    container_name: polen-rest
    volumes:
      - ./library:/scripts
    network_mode: host
    command: bash -c "pip install requests && python3 /scripts/polen_olivo.py"
    restart: always
